server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/glorious-youth?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: a752245683
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  redis:
    localhost: localhost
    port: 6379
    database: 0
    password:
    listen-pattern: __keyevent@0__:expired

rocketmq:
  consumer:
    consumer-group: YouthConsumerGroup
  producer:
    producerGroup: YouthProducerGroup
  namesrv-addr: 127.0.0.1:9876

youth:
  security:
    jwt-key: 6666666cao  #随便一个字符串
    token-expired-in: 86400000 #过期时间
  order:
    max-sku-limit: 999 #最大购买数量
    pay-time-limit: 3600 #最大支付时间
    pay-callback-host: http://ifg33n.natappfree.cc
    pay-callback-path: /v1/payment/wx/notify